### ISSUE TITLE
Is this project Maintained ?

### ISSUE THREAD

**Issue by Mubeen-hub** [alexanderankin/pyfpdf#16]
I'm little bit confused between pyfpdf and fpdf2,
What you have enhanced in fpdf2 ?
I want to use it with python 3.7 or 3.8, is this stable with python3.7 ?
Looking for a properly maintained library of python (3.7+), i want to generate some custom PDF that will contain text from dict.
Looking forward for your response.

**Comment by alexanderankin** [comment]
You can see here https://github.com/alexanderankin/pyfpdf/runs/1513416072 that
tests are passing on this library, the version 2.0.5 was released to enable
python 3.9 compatibility. This fork of the library is maintained.

There are some speed optimizations which I am releasing soon, which you can
preview https://pypi.org/project/fpdf2/2.1.0rc1/, there are some fixes
which will be released as `2.1.1rc1` soon. you can check the changelog
https://github.com/alexanderankin/pyfpdf/blob/master/CHANGELOG.md for full
details on what has changed.

**Comment by Mubeen-hub** [comment]
Thanks for the clarification @alexanderankin :+1:
