### ISSUE TITLE
multi_cell() behaviour difference between pyfpdf and pyfpdf2

### ISSUE THREAD

**Issue by Xtrem532** [alexanderankin/pyfpdf#35]
`multi_cell()`s used to modify the Document `self.y` coordinate in pyfpdf (adding their own height to it). In pyfpdf2, `self.y` stays the same. Is this intended, or a bug?

**Comment by Xtrem532** [comment]
Just found PR #7, applied the single line changed, problem fixed. Would recommend to merge #7.

**Comment by alexanderankin** [comment]
Created a PR #36 to make all green check marks happen for that fix

**Comment by Lucas-C** [comment]
Can you confirm this is OK now for your usage @Xtrem532 ? :)

**Comment by Xtrem532** [comment]
Yeah, Thanks!

**Comment by Lucas-C** [comment]
Perfect, closing this then
